version: 2.1
jobs:
  build_all:
    working_directory: ~/repo
    docker:
      - image: 'cimg/node:18.14.0'
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm install -g npm@9.4.2
      - restore_cache:
          key: 'dependency-cache-{{ checksum "package-lock.json" }}'
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: 'dependency-cache-{{ checksum "package-lock.json" }}'
          paths:
            - ./node_modules
      - run:
          name: Run lint
          command: npm run lint
  build_dev:
    working_directory: ~/repo
    docker:
      - image: 'cimg/node:18.14.0'
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm install -g npm@9.4.2
      - restore_cache:
          key: 'dependency-cache-{{ checksum "package-lock.json" }}'
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: 'dependency-cache-{{ checksum "package-lock.json" }}'
          paths:
            - ./node_modules
      - run:
          name: Run lint
          command: npm run lint
  build_main:
    working_directory: ~/repo
    docker:
      - image: 'cimg/node:18.14.0'
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm install -g npm@9.4.2
      - restore_cache:
          key: 'dependency-cache-{{ checksum "package-lock.json" }}'
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: 'dependency-cache-{{ checksum "package-lock.json" }}'
          paths:
            - ./node_modules
      - run:
          name: Run lint
          command: npm run lint
workflows:
  build_all:
    jobs:
      - build_all:
          filters:
            branches:
              ignore:
                - dev
                - main
  build_dev:
    jobs:
      - build_dev:
          filters:
            branches:
              only:
                - dev
  build_main:
    jobs:
      - build_main:
          filters:
            branches:
              only:
                - main
